### ISSUE TITLE
Tried to get invalid requirements: vehicle_bolt

### ISSUE THREAD

**Issue by drachs** [chaosvolt/cdda-tankmod-revived-mod#1]
Looks like "vehicle_bolt" was removed from the code and replaced with new objects, see ticket:

https://github.com/CleverRaven/Cataclysm-DDA/pull/46466

This causes this error every time I inspect a vehicle

![image](https://user-images.githubusercontent.com/450381/106826044-ec170500-663a-11eb-8a7d-9f56c66e310d.png)

Not 100% sure this tankmod revived, but it's the only non-mainline mod I've got installed.

Some people on discord have suggested that changing vehicle_bolt to vehicle_wrench_2 is the possible answer.

**Comment by chaosvolt** [comment]
Whoops, thank you for spotting that. I'd fixed that issue for a couple mods but not this one.

**Comment by chaosvolt** [comment]
There we go, do tell if anything else crops up.

**Comment by drachs** [comment]
Thanks!  Problem solved!
