### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by Anthraxmkv** [chaosvolt/cdda-tankmod-revived-mod#11]
DEBUG    : Error: Json error: data/mods/Tankmod_Revived_BN/ammo_effects.json:14:5: missing required field "range" in object: { "impact": { "damage_type": "cut", "amount": 400, "armor_multiplier": 3 }, "radius": 10 }
    

      "damage": 400,
      "fragment": { "impact": { "damage_type": "cut", "amount": 400, "armor_multiplier": 3 }, "radius": 10 }
    }
    ^

  },
  {

 FUNCTION : load_character_tab
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp
 LINE     : 1157
 VERSION  : BN d01ff98

**Comment by chaosvolt** [comment]
Whoops, thanks for spotting that.
