### ISSUE TITLE
[DDA] Mounted weapons name change

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-tankmod-revived-mod#13]
In a recent experimental update for DDA older entries in the "migration.json" were removed. 
https://github.com/CleverRaven/Cataclysm-DDA/pull/63915/files

Things that were named "mounted_x" seem to be "turret_x" now.

Unrelated, I just wanted to say thanks for working on two different versions of your various mods.

Edit: Looking through an old copy of the migration file it seems the "mounted_browning" is changed to "turret_m2browning" which is different then the other mounted to turret changed I was skimming through.

**Comment by chaosvolt** [comment]
Looks like the relevant PR is: https://github.com/CleverRaven/Cataclysm-DDA/pull/59563

**Comment by nemesis688** [comment]
Oh there is a lot more going on with this than I thought. I guess that's what I get when I skimmed over the "Testing" section of the other PR.

**Comment by chaosvolt** [comment]
Yep, very weird but...interesting. You can now mount random pistols and the like on turret mounts too. Interesting but the resulting parts being basically generated by hardcode seems like something that'd be a bit too much hassle to port over to BN, I suspect.

I'm gonna need to tinker with Arcana as well it seems, and chuck Noct a Cata++ update too, hmm.
