### ISSUE TITLE
Vehicle changes on base CDDA

### ISSUE THREAD

**Issue by Shelingar** [chaosvolt/cdda-tankmod-revived-mod#14]
looks like turrets used in this mod are no longer compatible with the base game.  It was working on experimental last time I updated my game.  I just did an update last night, and getting a bunch of errors.

for example

"unknown vehicle part mounted_browning in tank_m60_pattern"

Looks like they have removed most of the predefined turrets from the base game.  A comment on the repository may explain it:

"[Migrate turret vparts to generated ones]"
(https://github.com/CleverRaven/Cataclysm-DDA/commit/f4a445d2d7662fe6b6b6b4062687616d1880d042)

one comment in the current turrets.json may give a hint:

"//": "This item is used as base for turrets generated at runtime. m249 is random 'safe' choice, actual item is set at runtime in vpart_info::finalize.",

Sorry not sure where to go to dig further.

**Comment by chaosvolt** [comment]
Should be fixed by: https://github.com/chaosvolt/cdda-tankmod-revived-mod/commit/0f6dff01f3a864521af8d8be0a7efdf72a4ce367

I will need to yeet some similar updates at Arcana and one for Noct's Cata++ mod though.

**Comment by Shelingar** [comment]
That seems to have worked

**Comment by chaosvolt** [comment]
Nice.
