### ISSUE TITLE
[DDA] upss_charges to energy_drain and a few other new errors

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-tankmod-revived-mod#16]
`"ups_charges"` has been changed to `"energy_drain"` and some flags were added around them. This pull seems to go over it:

https://github.com/CleverRaven/Cataclysm-DDA/pull/63978

Also, I got a debug error about `damage_states` under `"abstract": "artillery_casing",` in items.json. I did a lazy search for it in DDAs github but I didn't find anything involving it. But they are doing (and partially did; item reinforcement has been yeeted) a big change with how item repair works so might be involved in that somehow.

Oh and `mon_zombie_flamer` seems to have been fully removed. I think it might have just been floating around in an obsoletion file somewhere until now. So an error about it being in mapgen.json is getting thrown at line 598.

**Comment by chaosvolt** [comment]
Ah nice, I'll have to work on this in the morning.

**Comment by chaosvolt** [comment]
Fixed with https://github.com/chaosvolt/cdda-tankmod-revived-mod/commit/a7cbba15622d778f918874e6338147bec4714b38
