### ISSUE TITLE
Invalid damage type

### ISSUE THREAD

**Issue by Outcognito** [chaosvolt/cdda-tankmod-revived-mod#2]
Can't start the game with tankmod enabled.
![Screenshot_2](https://user-images.githubusercontent.com/31615562/115282109-778c3680-a152-11eb-8cfa-f24e373fd73f.png)

**Comment by chaosvolt** [comment]
You're either using the DDA version with BN, or using it with an older stable release of DDA. I currently don't have a 0.E stable release of this mod set aside yet, and 0.F is supposed to be out there eventually.
