### ISSUE TITLE
120mm shells. Seems like the HEAT should be incendiary, but the depleted uranium causes fires instead.

### ISSUE THREAD

**Issue by cthae** [chaosvolt/cdda-tankmod-revived-mod#25]
Here's the screenshot of the comparison:
![](https://i.imgur.com/IrPtYQ5.png)

**Comment by cthae** [comment]
If it matters, I'm using the BN version.

**Comment by chaosvolt** [comment]
That's because HEAT is explosive, not literally heat-related: https://en.wikipedia.org/wiki/High-explosive_anti-tank
