### ISSUE TITLE
Tried to start object, but found '[', not '{'

### ISSUE THREAD

**Issue by Cockiner** [chaosvolt/cdda-tankmod-revived-mod#4]
Latest experimental. Deleting monsters.json seems to "fix" it. 
![error](https://user-images.githubusercontent.com/87234819/125165771-71609180-e166-11eb-9266-30486093aa6c.jpg)

**Comment by chaosvolt** [comment]
That'd be a consequence of https://github.com/CleverRaven/Cataclysm-DDA/pull/49439, I'll set aside a 0.F release of this mod and fix this when I get the time to.
