### ISSUE TITLE
0.F Unknown Flag 'Unstable_Wheel"

### ISSUE THREAD

**Issue by vinylspiders** [chaosvolt/cdda-tankmod-revived-mod#5]
<img src = "https://i.imgur.com/xxxrd4T.png"/>

I could be wrong here but seems like the proper way to denote a wheel as unstable (meaning, requiring more than one to balance the vehicle) is to simply omit the "STABLE" flag. There is no such flag as "UNSTABLE_WHEEL" as far as I can see.

Removing the flag fixes the error at any rate.

**Comment by chaosvolt** [comment]
Are you using the 0.F release of this mod or the experimental version from the repo's main page?

**Comment by vinylspiders** [comment]
0.F release

**Comment by chaosvolt** [comment]
I just double-checked, the 0.F Stable release does not have the `UNSTABLE_WHEEL` flag present anywhere in the JSON. You're either pairing the actual experimental branch of this mod with 0.F Stable, or pairing it with a very early 0.F Experimental build that predates this PR being merged: https://github.com/CleverRaven/Cataclysm-DDA/pull/48088

Use the correct release, available here: https://github.com/chaosvolt/cdda-tankmod-revived-mod/releases
