### ISSUE TITLE
I've got a bug with the last game's version (release 0.F-3 Frank-3). I'm trying to install this mod but it wont let me. I've got no knowledge on programing but since i'm on it i thought i would point this out. I've upploaded an image with the error log.

### ISSUE THREAD

**Issue by Diewitoh** [chaosvolt/cdda-tankmod-revived-mod#7]
![Sin título](https://user-images.githubusercontent.com/105590184/168471543-d548a8b1-630c-44f6-8078-7b161a2db916.png)

**Comment by chaosvolt** [comment]
Did you use the 0.F release for this mod? https://github.com/chaosvolt/cdda-tankmod-revived-mod/releases/tag/0.F

**Comment by chaosvolt** [comment]
Tested 0.F release with 0.F-3 DDA, no errors, so you were most definitely using the master branch with 0.F
