### ISSUE TITLE
Vehicle extends too far north

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-tankmod-revived-mod#9]
DEBUG    : In mapgen dirt_road, vehicle placement at x:[7,13], y:[3,18]: potential placement of vehicle out of bounds.  At rotation 270 the vehicle [vgroup_id farm_vehicles; vproto_id tractor_bandit] extends too far north, reaching coordinate y = -1 (should be at least 0)

 FUNCTION : virtual void jmapgen_vehicle::check(const string&, const mapgen_parameters&, const jmapgen_int&, const jmapgen_int&) const
 FILE     : src/mapgen.cpp
 LINE     : 2573
 VERSION  : d095623

 DEBUG    : In mapgen junkyard_1a, vehicle placement at x:[19,19], y:[18,18]: potential placement of vehicle out of bounds.  At rotation 270 the vehicle [vgroup_id junkyard_vehicles; vproto_id tank_m60_patton_mothballed] extends too far south, reaching coordinate y = 25 (should be at most 23)

 FUNCTION : virtual void jmapgen_vehicle::check(const string&, const mapgen_parameters&, const jmapgen_int&, const jmapgen_int&) const
 FILE     : src/mapgen.cpp
 LINE     : 2573
 VERSION  : d095623

 DEBUG    : In mapgen s_lot, vehicle placement at x:[3,3], y:[6,6]: potential placement of vehicle out of bounds.  At rotation 180 the vehicle [vgroup_id parkinglot; vproto_id howitzer_m109] extends too far west, reaching coordinate x = -1 (should be at least 0)

 FUNCTION : virtual void jmapgen_vehicle::check(const string&, const mapgen_parameters&, const jmapgen_int&, const jmapgen_int&) const
 FILE     : src/mapgen.cpp
 LINE     : 2573
 VERSION  : d095623

And so on...

**Comment by chaosvolt** [comment]
Hmm, will have to look into how to fix those, all of those are injections of mod vehicles into vanilla locations, so it seems like further cases of it no longer being able to handle large vehicle spawns. :/

**Comment by waveyl** [comment]
Is it going well?

**Comment by chaosvolt** [comment]
I haven't had the time to tinker with it as been juggling offline stuff a lot lately, so far it still mostly looks like an issue that's not going to be easy to work around.

**Comment by chaosvolt** [comment]
So, I'm looking into this and not able to reproduce this even after visiting various areas with vehicle group addition weights increased by a factor of 100, in recent version of BN. I'll test DDA in a bit.

**Comment by chaosvolt** [comment]
Okay yep, this is DDA-specific. This is a problem because this seems like it basically deliberately breaks being able to place large vehicles in areas that oughta have room for them... :/
